name: Bug Report
description: Report a bug or unexpected behavior in PCRE4J
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose the issue.

  - type: dropdown
    id: backend
    attributes:
      label: Backend
      description: Which PCRE4J backend are you using?
      options:
        - JNA (org.pcre4j.jna)
        - FFM (org.pcre4j.ffm)
        - Both
        - Unknown
    validations:
      required: true

  - type: dropdown
    id: api-level
    attributes:
      label: API Level
      description: Which API are you using?
      options:
        - regex (java.util.regex-compatible)
        - lib (Pcre2Code, Pcre2MatchData)
        - api (IPcre2 direct)
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: Output of `java -version`
      placeholder: "e.g., OpenJDK 21.0.1"
    validations:
      required: true

  - type: input
    id: pcre2-version
    attributes:
      label: PCRE2 Library Version
      description: Version of the native PCRE2 library installed on your system
      placeholder: "e.g., 10.42"
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your OS and version
      placeholder: "e.g., Ubuntu 24.04, macOS 14.2, Windows 11"
    validations:
      required: true

  - type: input
    id: pcre4j-version
    attributes:
      label: PCRE4J Version
      description: Version of PCRE4J you are using
      placeholder: "e.g., 0.4.3"
    validations:
      required: true

  - type: textarea
    id: pattern
    attributes:
      label: Regex Pattern
      description: The regular expression pattern
      render: text
    validations:
      required: false

  - type: textarea
    id: input
    attributes:
      label: Input String
      description: The input string being matched (if applicable)
      render: text
    validations:
      required: false

  - type: textarea
    id: code
    attributes:
      label: Code to Reproduce
      description: Minimal code example that reproduces the issue
      render: java
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include stack traces if applicable)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help diagnose the issue
    validations:
      required: false
