name: Feature Request
description: Suggest a new feature or enhancement for PCRE4J
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem are you trying to solve? What's your use case?
      placeholder: "I'm trying to... but currently..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds have you considered?
    validations:
      required: false

  - type: dropdown
    id: scope
    attributes:
      label: Affected Area
      description: Which part of PCRE4J does this affect?
      options:
        - api (IPcre2 interface)
        - lib (Pcre2Code, contexts, utilities)
        - jna (JNA backend)
        - ffm (FFM backend)
        - regex (java.util.regex compatibility)
        - documentation
        - build/tooling
        - other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, code examples, or references that would help
    validations:
      required: false
